# Site settings
title: Gyan passed down from one batch to another
description: IEEE NITK is a student branch of IEEE located at NITK Surathkal. This section called Gyan serves as a collection of experiences of various seniors throughout the years.
baseurl: "/gyan" # the subpath of your site, e.g. /blog
url: "https://ieee.nitk.ac.in" # the base hostname & protocol for your site e.g. http://ieeenitk.org

# User settings
username: IEEE-NITK 
user_description: IEEE Student chapter at NITK Surathkal
description: Gyan passed down from one batch to another
email: ieee@nitk.edu.in
twitter_username: IEEE_NITK 
github_username: IEEE-NITK
facebook_username: IEEENITK

#Facebook Sharing
facebook_app_id: 0011038251882641

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /gyan
  - title: Tags
    url: /gyan/tags
  - title: Main Website
    url: /
  - title: Blog
    url: /blog

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# extra plugins
plugins_dir: 
  ['jekyll-paginate']

# Gems
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]

#make 5 articles per page
paginate: 5
paginate_path: "/page:num/"